# Generated by Django 2.2.28 on 2023-01-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='domain_name',
            field=models.CharField(choices=[('django', 'django'), ('react', 'react')], default=('django', 'django'), max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='framework',
            field=models.CharField(choices=[('web', 'web'), ('mobile', 'mobile')], default=('web', 'web'), max_length=6),
        ),
    ]
